<<<<<<< Updated upstream
name: Actionlint (GHA syntax)

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"
=======
---
name: YAML Lint

'on':
  pull_request:
    branches: ["main"]
    paths: [".github/workflows/**/*.yml", ".github/workflows/**/*.yaml"]
>>>>>>> Stashed changes

permissions:
  contents: read

jobs:
<<<<<<< Updated upstream
  actionlint:
    name: Actionlint (GHA syntax)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Versión estable (no usar @v1)
      - name: Run actionlint
        uses: rhysd/actionlint@v1.6.27
        # Si quieres permitir expresiones no estándar, puedes pasar flags:
        # with:
        #   args: -shellcheck= -format=sarif
        
=======
  yamllint:
    name: yamllint (YAML format)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: |
          sudo apt-get update -y
          sudo apt-get install -y yamllint
      - name: Run yamllint
        run: |
          yamllint -d "{extends: default, rules: {line-length: {max: 160}}}" .github/workflows
>>>>>>> Stashed changes
