---
name: Build & Test (.NET)

'on':
  workflow_call:
    inputs:
      app_dir:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.app_dir }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - run: dotnet restore
      - run: dotnet build --configuration Release --no-restore
<<<<<<< Updated upstream
      - run: dotnet test --no-build --verbosity normal
      
=======
      - run: dotnet test --no-build --verbosity normal
>>>>>>> Stashed changes
