---
name: Build & Test (Java Maven)

'on':
  workflow_call:
    inputs:
      app_dir:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.app_dir }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
      - run: mvn -B -q -DskipTests=false clean verify
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-reports
          path: "**/surefire-reports/*.xml"
          if-no-files-found: ignore
          