---
name: Build & Test (Node + React)

'on':
  workflow_call:
    inputs:
      app_dir:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.app_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: ${{ inputs.app_dir }}/package-lock.json
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Test
        run: npm test --if-present -- --ci --watch=false
      - name: Build
        run: npm run build --if-present
      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-reports
          path: |
            **/jest-junit*.xml
            **/test-results/**/*.xml
          if-no-files-found: ignore
