---
name: Build & Test (Node + React)

'on':
  workflow_call:
    inputs:
      app_dir:
        description: "Directorio raíz de la app dentro del repo"
        required: true
        type: string
      node_version:
        description: "Versión de Node a usar"
        required: false
        default: "20"
        type: string

permissions:
  contents: read

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.app_dir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 👇 Sin cache para evitar warnings cuando no existe package-lock.json
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      # 👇 Usa npm ci si hay lockfile; si no, cae a npm i (sin audit/fund para CI)
      - name: Install deps (ci if lockfile, else install)
        shell: bash
        run: |
          if [ -f package-lock.json ]; then
            echo "Found package-lock.json → npm ci"
            npm ci --no-audit --no-fund
          else
            echo "No package-lock.json → npm i"
            npm i  --no-audit --no-fund
          fi

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm test --if-present -- --ci --watch=false

      - name: Build
        run: npm run build --if-present

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: unit-test-reports
          path: |
            **/jest-junit*.xml
            **/test-results/**/*.xml
          if-no-files-found: ignore
