
name: Dependency Review
on: { workflow_call: {} }
permissions: { contents: read, pull-requests: read, security-events: write }
jobs:
  dep:
    name: Dependency Review
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/dependency-review-action@v4
        with: { fail-on-severity: high }
