---
name: Dependency Review

'on':
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Dependency Review
<<<<<<< Updated upstream
        uses: actions/dependency-review-action@v4
        
=======
        uses: actions/dependency-review-action@v4
>>>>>>> Stashed changes
