name: Gitleaks

'on':
  workflow_call:
    inputs:
      app_dir:
        required: false
        type: string
        default: "."

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.24.3/gitleaks_8.24.3_linux_x64.tar.gz \
          | tar -xz -C /usr/local/bin gitleaks
          gitleaks version

      - name: Run Gitleaks (generate SARIF)
        working-directory: ${{ inputs.app_dir }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gitleaks detect --no-git --redact \
            --report-format sarif \
            --report-path "${{ github.workspace }}/gitleaks.sarif"

      - name: Upload SARIF (best effort)
        if: always() && hashFiles('gitleaks.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
