---
name: Gitleaks

'on':
  workflow_call:
    inputs:
      app_dir:
        required: false
        type: string
        default: "."

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      pull-requests: read
    env:
      # Necesario desde el breaking change de Gitleaks para escanear PRs
      GITHUB_TOKEN: ${{ github.token }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # La acción ya trae el comando por dentro; no pases 'args'
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2

      # Best-effort: sube solo si el archivo existe
      - name: Upload SARIF (best effort)
        if: always() && hashFiles('gitleaks.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
