---
name: Gitleaks

'on':
  workflow_call:
    inputs:
      app_dir:
        required: false
        type: string
        default: "."

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Scan
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --no-git --redact --report-format sarif --report-path gitleaks.sarif
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
