---
name: Gitleaks (secrets)

on:
  pull_request:
    branches: [develop, staging, main]
  push:
    branches: [develop, staging, main]

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Acción oficial. No pasamos "args" para evitar el warning de inputs.
      # La acción por defecto detecta leaks y falla si encuentra alguno.
      # Si quieres flags personalizados, te muestro cómo abajo.
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Publica el reporte SARIF si la acción lo genera (últimas versiones lo soportan);
      # si no aparece el archivo, no sube nada y no falla.
      - name: Upload SARIF (best effort)
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
