---
name: Gitleaks

'on':
  workflow_call:
    inputs:
      app_dir:
        required: false
        type: string
        default: "."

permissions:
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        