---
name: Gitleaks (secrets)

on:
  workflow_call:
    inputs:
      app_dir:
        required: false
        type: string
        default: "."
    secrets:
      token:
        required: false

permissions:
  contents: read
  security-events: write

jobs:
  gitleaks:
    name: Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Esta acción descarga y deja gitleaks en PATH, pero no acepta "args"
      - name: Install gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Ejecutamos gitleaks con los flags que necesitas y generamos SARIF
      - name: Run gitleaks detect
        run: |
          gitleaks version
          gitleaks detect \
            --no-git \
            --source "${{ inputs.app_dir }}" \
            --redact \
            --report-format sarif \
            --report-path gitleaks.sarif

      # Subimos el SARIF sólo si existe (best effort)
      - name: Upload SARIF (best effort)
        if: always() && hashFiles('gitleaks.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
