<<<<<<< Updated upstream
<<<<<<< Updated upstream

=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
---
name: JaCoCo Coverage

'on':
  workflow_call:
    inputs:
      app_dir:
        required: true
        type: string
<<<<<<< Updated upstream
<<<<<<< Updated upstream
      coverage_min:
        required: false
        type: string
        default: "0"

jobs:
  coverage:
    name: JaCoCo (informativo)
=======

jobs:
  coverage:
>>>>>>> Stashed changes
=======

jobs:
  coverage:
>>>>>>> Stashed changes
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.app_dir }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven
<<<<<<< Updated upstream
<<<<<<< Updated upstream
      - name: Run tests & jacoco report
        run: mvn -q -DskipTests=false test jacoco:report
      - name: Parse coverage
        id: cov
        run: |
          FILE=target/site/jacoco/jacoco.xml
          if [ -f "$FILE" ]; then
            MISSED=$(grep -oP 'counter type="LINE" missed="\K[0-9]+' "$FILE" | head -1 || echo 0)
            COVERED=$(grep -oP 'counter type="LINE".*covered="\K[0-9]+' "$FILE" | head -1 || echo 0)
            TOTAL=$((MISSED + COVERED))
            PCT=0
            if [ "$TOTAL" -gt 0 ]; then PCT=$((100 * COVERED / TOTAL)); fi
            echo "pct=$PCT" >> "$GITHUB_OUTPUT"
          else
            echo "pct=0" >> "$GITHUB_OUTPUT"
          fi
      - name: Summary
        run: |
          echo "### JaCoCo Coverage" >> $GITHUB_STEP_SUMMARY
          echo "**Line Coverage:** ${{ steps.cov.outputs.pct }}%" >> $GITHUB_STEP_SUMMARY
          echo "_(informativo; umbral mínimo: ${{ inputs.coverage_min }}%)_"
    continue-on-error: true
=======
=======
>>>>>>> Stashed changes
      - run: mvn -B test
      - uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
<<<<<<< Updated upstream
          path: ${{ inputs.app_dir }}/target/site/jacoco/index.html
>>>>>>> Stashed changes
=======
          path: ${{ inputs.app_dir }}/target/site/jacoco/index.html
>>>>>>> Stashed changes
