---
name: JaCoCo Coverage

'on':
  workflow_call:
    inputs:
      app_dir:
        required: true
        type: string

jobs:
  coverage:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.app_dir }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven
      - run: mvn -B test
      - uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: ${{ inputs.app_dir }}/target/site/jacoco/index.html
          