---
name: Trivy SCA

'on':
  workflow_call:
    inputs:
      app_dir:
        required: true
        type: string

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy SCA
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: ${{ inputs.app_dir }}
          ignore-unfixed: true
          severity: HIGH,CRITICAL
          