<<<<<<< Updated upstream
<<<<<<< Updated upstream

=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes
---
name: Trivy SCA

'on':
  workflow_call:
    inputs:
      app_dir:
        required: true
        type: string
<<<<<<< Updated upstream
<<<<<<< Updated upstream
        required: false
        default: "."
      severity:
        type: string
        required: false
        default: "HIGH,CRITICAL"
      ignore_unfixed:
        type: string
        required: false
        default: "true"
      fail_on_findings:
        type: string
        required: false
        default: "true"
=======
>>>>>>> Stashed changes
=======
>>>>>>> Stashed changes

permissions:
  contents: read
  security-events: write

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
<<<<<<< Updated upstream
<<<<<<< Updated upstream
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Trivy SCA
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: fs
          scanners: vuln
          format: sarif
          output: trivy.sarif
          working-directory: ${{ inputs.app_dir }}
          severity: ${{ inputs.severity }}
          ignore-unfixed: ${{ inputs.ignore_unfixed }}
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy.sarif
      - name: Fail on findings
        if: ${{ inputs.fail_on_findings == 'true' }}
        run: |
          COUNT=$(jq '[.runs[].results] | map(length) | add' trivy.sarif)
          test "${COUNT:-0}" -eq 0
=======
      - uses: actions/checkout@v4
      - name: Run Trivy SCA
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: ${{ inputs.app_dir }}
          ignore-unfixed: true
          severity: HIGH,CRITICAL
>>>>>>> Stashed changes
=======
      - uses: actions/checkout@v4
      - name: Run Trivy SCA
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: ${{ inputs.app_dir }}
          ignore-unfixed: true
          severity: HIGH,CRITICAL
>>>>>>> Stashed changes
