---
name: YAML Lint
'on':
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"

permissions:
  contents: read

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Escribir config
        run: |
          cat > .yamllint.yml <<'CFG'
          extends: default
          rules:
            document-start:
              present: true
            line-length:
              max: 160
            # mantén estas activas; son las que te están pegando:
            trailing-spaces: {level: error}
            new-line-at-end-of-file: {level: error}
          CFG

      # 1) Anotaciones en la UI
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ".github/workflows"
          format: github
          strict: true

      # 2) Salida legible en logs (mismo análisis)
      - name: yamllint (stdout)
        run: |
          python3 -m pip install --user yamllint
          ~/.local/bin/yamllint -c .yamllint.yml -f standard .github/workflows
