---
name: YAML Lint

'on':
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"

permissions:
  contents: read

jobs:
  yamllint:
    name: yamllint (YAML format)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: |
          sudo apt-get update -y
          sudo apt-get install -y yamllint

      - name: Run yamllint
        run: |
          cat > .yamllint.yml <<'CFG'
          extends: default
          rules:
            line-length:
              max: 160
          CFG
          yamllint -c .yamllint.yml .github/workflows
          