---
name: YAML & Workflow Lint

on:
  pull_request:
    branches: ["develop", "staging", "main"]
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"

permissions:
  contents: read

jobs:
  lint:
    name: yamllint + actionlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Config de yamllint pensada para workflows con líneas largas y strings inline
      - name: Write yamllint config
        run: |
          cat > .yamllint.yml <<'CFG'
          extends: default
          rules:
            document-start:
              present: true
            line-length:
              max: 300
              allow-non-breakable-words: true
              allow-non-breakable-inline-mappings: true
            trailing-spaces:
              level: error
            new-line-at-end-of-file:
              level: error
            truthy: disable
            brackets: disable
            comments: disable
            indentation: disable
            colons: disable
            braces: disable
            empty-lines: disable
          CFG

      - name: Run yamllint (strict)
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ".github/workflows"
          format: github
          strict: true

      # actionlint detecta problemas propios de GitHub Actions que yamllint no ve
      - name: Run actionlint
        uses: rhysd/actionlint@v1.6.27