---
name: YAML Lint

'on':
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"

permissions:
  contents: read

jobs:
  yamllint:
    name: yamllint (YAML format)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ibiqlik/action-yamllint@v3
        with:
          format: github
          strict: true
          # Config en YAML (evitamos JSON embebido en una sola línea)
          config_data: |
            extends: default
            rules:
              line-length:
                max: 160