---
name: YAML Lint

'on':
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/**/*.yml"
      - ".github/workflows/**/*.yaml"

permissions:
  contents: read

jobs:
  yamllint:
    name: yamllint (YAML format)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Write yamllint config
        run: |
          cat > .yamllint.yml <<'CFG'
          extends: default
          rules:
            document-start:
              present: true
            line-length:
              max: 160
            trailing-spaces:
              level: error
            new-line-at-end-of-file:
              level: error
            truthy: disable
            brackets: disable
            comments: disable
            indentation: disable
          CFG

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: ".github/workflows"
          format: github
          strict: true
